#! /bin/sh

OUTPUT=$(xrandr | awk '/ connected/ {print $1}')

for output in $OUTPUT; do
    if [ "$output" != "" ]; then
        xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
        xrandr --addmode "$output" 1920x1080_60.00
        xrandr -s 1920x1080_60.00
    fi
done
