#! /bin/sh

old_state=$(cat /sys/class/power_supply/BAT1/status)


if [ "$old_state" = "Charging" ];
then
    gksu ~/.config/polybar/Scripts/cpugovernor performance
else
    gksu ~/.config/polybar/Scripts/cpugovernor powersave
fi


while true; do
    # Get current state
    current_state=$(cat /sys/class/power_supply/BAT1/status)

    # If state has changed
    if [ "$old_state" != "$current_state" ];
    then
	if [ "$current_state" = "Charging" ];
	then
	    echo "State changed to charging!"
	    gksu ~/.config/polybar/Scripts/cpugovernor performance

	elif [ "$current_state" = "Discharging" ];
	then
	    echo "State changed to discharging!"
            gksu ~/.config/polybar/Scripts/cpugovernor powersave

	else
	    echo "State unchanged."
	fi

    fi
    # Save current state to old state
    old_state=$current_state
    sleep 5
done
