#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

echo "Checking touch in firefox..."
longstring=$(cat $(which firefox))
substring="MOZ_USE_XINPUT2=1"

if [[ $longstring == *"$substring"* ]]; then
    echo "Touch is enabled. Nothing to do."
else
    echo "Enabling touch..."
    zensu ~/.i3/Scripts/firefox-touch-enabler
fi
