#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'


# name: firefox-touch-nabler:
# Enables touch in firefox if it isn't already
# suggested usage: ./firefox-touch-enable

content='#! /bin/sh

# enable touch scroll in firefox
Exec=env MOZ_USE_XINPUT2=1 exec /usr/lib/firefox/firefox "$@"'

echo
echo "$content"
echo "$content" > /usr/bin/firefox

exit 0
