#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

displayUsage() {
    echo '
usage:  name [-t|-h]
operations:
    screen-idle {-h help} shows this dialogue
    screen-idle {-t help} set minimum idletime [s]
'
}

idletime=60
while getopts ":ht:" opt; do
    case ${opt} in
	t)
	   idletime="$OPTARG"
	;;
	h)
	    displayUsage
	    exit 1
	    ;;
	\?)
	    echo "Invalid option: $OPTARG" 1>&2
	    exit 2
	    ;;
	:)
	    echo "Invalid option: $OPTARG requires an argument" 1>&2
	    exit 2
	    ;;
    esac
    shift
done

while true; do
    [ "$(xprintidle)" -gt "$(( idletime * 1000 ))" ] && \
	[ xrandr | awk '/primary/ {print $1}' ] && ~/.i3/Scripts/toggle-screen
    sleep 1
done
