#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

displayUsage() {
    echo '
<>  angle brackets for required parameters: ping <hostname>
[]  square brackets for optional parameters: mkdir [-p] <dirname>
... ellipses for repeated items: cp <source1> [source2…] <dest>
 |  vertical bars for choice of items: netstat {-t|-u}

usage:
screen-idle [time]
One optional argument. This sets the idle
time before dimming the screen in seconds.
'
}

time=$(( 60 * 1000 ))
while getopts ":h" opt; do
    case ${opt} in
	h)
	    displayUsage
	    exit 1
	    ;;
	\?)
	    echo "Invalid option: $OPTARG" 1>&2
	    exit 2
	    ;;
    esac
    shift
done

if [ $# -eq 1 ]
then
    time=$(( $1 * 1000))
fi

while true; do
    [ "$(xprintidle)" -gt "$time" ] && ~/.i3/Scripts/toggle-screen
    sleep 1
done
