#! /bin/bash

# Check if wlan is softblocked
BLOCKED=$(wifi | awk '{print $3}')

if [ "$BLOCKED" == "on" ]
then
    rfkill block wifi
    notify-send -t 3000 "Toggle WiFi" "Wifi turned off!"
elif [ "$BLOCKED" == "off" ]
then
    rfkill unblock wifi
    notify-send -t 3000 "Toggle WiFi" "WiFi turned on!"
fi
