#!/bin/sh
# /usr/bin/i3exit

lock() {
    betterlockscreen -l dimblur
}

# with openrc use loginctl
[[ $(cat /proc/1/comm) == "systemd" ]] && logind=systemctl || logind=loginctl

case "$1" in
    lock)
	lock 
        ;;
    logout)
        i3-msg exit
        ;;
    switch_user)
        dm-tool switch-to-greeter
        ;;
    suspend)
        systemctl suspend -i && lock
        ;;
    hibernate)
        systemctl hibernate -i && lock
        ;;
    reboot)
	~/.i3/Scripts/i3-resurrect-save-all
        $logind reboot
        ;;
    shutdown)
	~/.i3/Scripts/i3-resurrect-save-all
        $logind poweroff
        ;;
    *)
        echo "== ! i3exit: missing or invalid argument ! =="
        echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
        exit 2
esac

exit 0
