#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

if type "xrandr"; then
    echo "found screens"
    for m in $(xrandr --query | grep " connected" | awk '{print $1}'); do
	MONITOR=$m polybar -q --reload main &
    done
else
    echo "no screens connected"
    polybar -q --reload main &
fi

echo "done"
