#! /bin/sh
notify-send -t 5000 "Reloading Polybar"

notify-send -t 2000 "Polybar Refresh" "waiting for processes to die"
killall -w polybar
notify-send -t 2000 "Polybar Refresh" "all processes killed"

# Launch bar
# sh ~/.config/polybar/polybar &
~/.config/polybar/all-the-polybars &
