#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# # set current time
# idleTime=$(date +%s)
# lessThan="120"

# while true;
# do
#     #get pairing- and power-status yes/no
#     bltout=$(echo "info" | bluetoothctl | awk '/Paired/{print $2}')
#     BLTPAIRED=$([ "$bltout" ] && echo "$bltout" || echo no)
#     BLTPOWER=$(echo "show" | bluetoothctl | awk '/Powered/{print $2}')

#     if [ "$BLTPAIRED" = 'yes' ]
#     then
# 	# if connected renew idleTime
# 	idleTime=$(date +%s)
#     elif [ "$BLTPAIRED" = 'no' ]
#     then
# 	# if time difference exceed 3 minutes
# 	timeDiff=$(( $(date +%s) - "$idleTime" ))
# 	if [ "$(( timeDiff / 60 ))" -gt "$lessThan" ] && [ "$BLTPOWER" = 'yes' ]
# 	then
# 	    # turn off bluetooth
# 	    rfkill block bluetooth &

# 	    # kill autoconnect daemon
# 	    pkill -f bluetooth-autoconnect &
# 	    notify-send -t 5000 "Bluetooth idling" "turning off bluetooth."
# 	    idleTime=-1
# 	fi
#     fi
#     sleep 1
# done
