#! /bin/sh
level=$2

if [ "$1" = "up" ];
then
    xbacklight -inc "$level" -time 150
elif [ "$1" = "down" ];
then
    xbacklight -dec "$level" -time 150
else
    echo "Script should be called with 'up' or 'down'"
fi

sleep 0.1
~/.i3/Scripts/print_brightness.sh
