#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

PATHTOIMAGES=$1
if [ -d "$PATHTOIMAGES" ];
then
    echo -e "Path: ## $PATHTOIMAGES ## exists"
    randimg=$(find "$PATHTOIMAGES"*/*.* | shuf -n 1)
    echo "Random image: $randimg"
    feh --bg-fill "$randimg"
    betterlockscreen -u "$randimg" -b 1
    notify-send -t 2000 "feh-random-wallpaper" "Done preparing lockscreen"
else
    echo -e "Path: $PATHTOIMAGES\nDOES NOT exist"
fi
