#! /bin/sh
# name: firefox-touch-nabler:
# Enables touch in firefox if it isn't already
# suggested usage: ./firefox-touch-enable

substring='MOZ_USE_XINPUT2=1'
full=$(cat /usr/bin/firefox)

# Check if substring is in the file
if [ -z "${full##*$substring*}" ]
then
    # if it is - do nothing
    echo "Firefix has touch enabled. Nothing to do..."
else
    # if it is not - rewrite the file to open firefox with touch enabled
    echo "Enabling touch infirefox"
    gksu echo '#! /bin/sh

# Enable touch scroll in firefox
Exec=env MOZ_USE_XINPUT2=1 exec /usr/lib/firefox/firefox "$@"' > /usr/bin/firefox
fi
