#! /bin/sh

# check if touch has been enabled
sub='MOZ_USE_XINPUT2=1'
full=$(cat /usr/bin/firefox)

if [ -z "${full##*$sub*}" ]
then
    echo "Firefix has touch enabled. Nothing to do..."
else
    echo "Enabling touch infirefox"
    gksu ~/.i3/Scripts/firefox_fix_manjaro 
fi
