#! /bin/bash

# Check if wlan is softblocked
BLOCKED=$(rfkill list wifi | awk '/Soft blocked/{print $3}' | uniq)

if [ "$BLOCKED" == "no" ]
then
    rfkill block wifi
    notify-send -t 3000 "Toggle WiFi" "Wifi turned off!"
elif [ "$BLOCKED" == "yes" ]
then
    rfkill unblock wifi
    notify-send -t 3000 "Toggle WiFi" "WiFi turned on!"
fi
