alias ll='exa --long --group --icons --git --git-ignore --header'
alias la='exa --long --group --icons --git --header --all'
alias tree='exa --tree'
alias tll='exa --tree --long --group --icons --git --git-ignore --header'
alias tla='exa --tree --long --group --icons --git --header --all'
