#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

checkBluetooth() {
    id=$(echo info | bluetoothctl | awk '/Device/{print $2}' | sed 's/:/_/g')
    [ -z "${device##*$id*}" ] && [ -n "$id" ] && HEADPHONEBLUETOOTH=1 || HEADPHONEBLUETOOTH=0
}

checkUSBDAC() {
    id='usb'
    [ -z "${device##*$id*}" ] && [ -n "$id" ] && USBDACS=1 || USBDACS=0
}

checkHeadPhone() {
    id='alsa'
    state=$(amixer -c 0 contents | grep -iA2 'headphone jack' | grep -oP '=\K(on|off)')
    [ -z "${device##*$id*}" ] && [ "$state" = 'on' ] && HEADPHONEJACK=1 || HEADPHONEJACK=0
}

checkMicrophone() {
    state=$(amixer sget Capture toggle | grep -Pom1 '(?<=\[)(on|off)(?=\])')
    [ "$state" = 'on' ] && MICROPHONE=1 || MICROPHONE=0
}


# Checkig whether Volume is muted [on/off]
VOLUMESTATE=$(amixer -D pulse sget Master | grep -Po 'Left:.*\K(on|off)')

# detirmine type of output
if [ "$VOLUMESTATE" = "on" ]; then
    # Get Default Sink i.e. activate sound output
    device=$(pactl info | awk '/Default Sink/{print $3}')

    # Check microphone and init output string
    checkMicrophone
    [ "$MICROPHONE" = 1 ] && OUTPUT="" || OUTPUT=" "
    # Check if jack is connected [on/off]
    checkHeadPhone

    # # Check for usb soundcard
    checkUSBDAC

    # Check for Bluetooth headphones
    checkBluetooth

    # echo '$HEADPHONEJACK'
    if [ "$USBDACS" = 1 ];
    then
    	OUTPUT+=" VOL"
    elif [ "$HEADPHONEBLUETOOTH" = 1 ];
    then
    	OUTPUT+=" VOL"
    elif [ "$HEADPHONEJACK"  = 1 ];
    then
	OUTPUT+=" VOL"
    else

	OUTPUT+="VOL"
    fi

    # Get volume
    MASTER_VOLUME=$(amixer -D pulse sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }')
else
    OUTPUT="VOL "
    MASTER_VOLUME=''
fi

echo "$OUTPUT $MASTER_VOLUME"
