#! /bin/sh


# Volume [on/off]
VOLUMESTATE=$(amixer -D pulse sget Master | grep -Po 'Left:.*\K(on|off)')
if [ "$VOLUMESTATE" = "on" ]; then
    # Headphones connected [on/off]
    HEADPHONEJACK=$(amixer -c 0 contents | grep -iA2 'headphone jack' | grep -oP '=\K(on|off)')
    USBDACS=$(alsa-capabilities -l u)
    HEADPHONEBLUETOOTH=$(echo "info" | bluetoothctl | grep Name || echo '')
    if [ "$USBDACS" ];
    then
	OUTPUT=" VOL"

    elif [ "$HEADPHONEJACK" = "on" ];
    then
	OUTPUT=" VOL"
    elif [ "$HEADPHONEBLUETOOTH" ];
    then
    	OUTPUT=" VOL"
    else

	OUTPUT="VOL"
    fi

    # Get volume
    MASTER_VOLUME=$(amixer -D pulse sget Master | grep -Po ".*Left:.*\[\K([0-9]+%)")
else
    OUTPUT="VOL "
    MASTER_VOLUME=''
fi

echo "$OUTPUT $MASTER_VOLUME" 
