#! /bin/sh

# longlat=$(whereami -r | grep -Eo "([0-9]{0,2}\.[0-9]{4})")
longitude=$(whereami -r | awk '/longitude/ {print}' | grep -Eo '[0-9]{2}\.[0-9]{4}')
latitude=$(whereami -r | awk '/latitude/ {print}' | grep -Eo '[0-9]{2}\.[0-9]{4}')

echo "Starting redhift at lat:$latitude and lon:$longitude:"
redshift -l $latitude:$longitude
