#! /bin/sh

oldState=$(cat /sys/class/power_supply/BAT1/status)

while true; do
    curState=$(cat /sys/class/power_supply/BAT1/status)

    if [ "$curState" = "Charging" ] && [ "$oldState" != "$curState" ]; then
	echo "State changed to charging!"
	sudo ~/.config/polybar/Scripts/cpugovernor performance
    elif [ "$curState" = "Discharging" ] && [ "$oldState" != "$curState" ]; then
	echo "State changed to discharging!"
        sudo ~/.config/polybar/Scripts/cpugovernor powersave
    else
	echo "unknown state."
    fi

    sleep 5
done
