#! /bin/sh

OLD_VERSION=$(cat .firefox_version)
CUR_VERSION=$(firefox --version)
echo "old: $OLD_VERSION"
echo "cur: $CUR_VERSION"
if [ "$OLD_VERSION" != "$CUR_VERSION" ];
then
    gksu ~/.i3/Scripts/firefox_fix_manjaro 
    echo "Enabling touch infirefox"
    echo "$(firefox --version)" > .firefox_version
else
    echo "Firefix is update. Nothing to do..."
fi
