#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# remove old saves
rm -f ~/.i3/i3-resurrect/*

# find running workspaces
workspaces=$(i3-msg -t get_workspaces | jq '.[] | .name')
echo "Found workspaces: $workspaces"

# Save workspaces with programs running
for ws in ${workspaces[*]}; do
    temp="${ws%\"}"
    temp="${temp#\"}"
    echo "saving $temp"
    i3-resurrect save -w $temp
done

notify-send "i3-resurrect" "Saved all workspaces"
