#! /bin/bash

var=$(wifi)
echo var
if [ "$var" == "wifi      = on" ]; then
    gksu rfkill block wifi
    notify-send "Toggle WiFi" "Wifi turned off!"
else
    gksu rfkill unblock wifi
    notify-send "Toggle WiFi" "WiFi turned on!"
fi
