#! /bin/bash

# Name: Toggle bluetooth
# Description: Small script to turn toggle bluetooth 
# Arguments: No arguemnts
# example suggested usage: toggle-bluetooth

isPowered=$(echo show | bluetoothctl | awk '/Powered/ {print $2}')
if [[ "$isPowered" == "no" ]]; then
    gksu rfkill unblock bluetooth
    notify-send "Toggle bluetooth" "Bluetooth turned on!"
elif [[ "$isPowered" == "yes" ]]; then
    gksu rfkill block bluetooth
    notify-send "Toggle bluetooth" "Bluetooth turned off!"
else
    echo "Unknown bluetoothstate"
fi

