#! /bin/bash

var=$(bluetooth | awk '{print $3}')
if [[ "$var" == "off" ]]; then
    gksu rfkill unblock bluetooth
    notify-send "Toggle bluetooth" "Bluetooth turned on!"
elif [[ "$var" == "on" ]]; then
    gksu rfkill block bluetooth
    notify-send "Toggle bluetooth" "Bluetooth turned off!"
else
    echo "Unknown bluetoothstate"
fi

