#! /bin/sh

###################################################################################
# Screen toggle                                                                   #
# A program to toggle a screen on or off nicely by fading in or out using         #
# xbacklight.	                                                                  #
# argument 1 - screen name						          #
# expected input/output: only takes one argument which is the screen to be 	  #
#                        toggled. If no name is passed the default screen will be #
#                        fetched and used.					  #
# example suggested usage: ./screen-toggle					  #
###################################################################################

# Functions to turn on/off screen 
turn_on() {
    # get previous brightness and turn on screen to same brightness 
    CURRENT_BRIGHTNESS=$(cat ~/.i3/Scripts/.currentBrightness)
    OLD_PROFILE=$(cat  ~/.i3/Scripts/.currentProfile)

    xrandr --output "$INTERNAL_OUTPUT" --auto
    xrandr -s "$OLD_PROFILE"	

    sleep 0.25
    xbacklight -inc "$CURRENT_BRIGHTNESS" -time 500
}

turn_off() {
    # save current brightness for later use, dim and then turn off the screen
    CURRENT_BRIGHTNESS=$(xbacklight -get)
    PROFILE=$(xrandr -q |awk '/\*/{print $1}')
    
    echo "$PROFILE" > ~/.i3/Scripts/.currentProfile
    echo "$CURRENT_BRIGHTNESS" > ~/.i3/Scripts/.currentBrightness 
    xbacklight -dec "$CURRENT_BRIGHTNESS" -time 300
    xrandr --output "$INTERNAL_OUTPUT" --off 
}

wait_for_user(){
    # Wait for user to interact with computer
    while [ "$USER_IDLE_TIME" -gt 500 ]; do
	sleep 0.5
	USER_IDLE_TIME=$(xprintidle)
    done
}

##########################################################################
# Actual script                                                          #
##########################################################################
# Fetch screen if not provided by the user
if [ $# -eq 0 ]; then
    PRIMARY_OUTPUT=$(xrandr | awk '/primary/ {print $1}')
    INTERNAL_OUTPUT=$PRIMARY_OUTPUT	# 
else
    INTERNAL_OUTPUT=$1
fi

# set user idle time to be used in loop
USER_IDLE_TIME=501

# Check if default screen is on/off to determine if it should go off/on
if ! xrandr --prop | grep eDP1 | grep mm
then
    turn_off
    wait_for_user
    turn_on
else
    turn_on
fi

exit 0
