#! /bin/sh

ans=$(pgrep screenrotator)

if [ "$ans" = "" ]; then
    screenrotator &
    notify-send "Screen rotation" "turned on"
else
    killall screenrotator
    notify-send "Screen rotation" "turned off"
fi
&

