#!/bin/sh

lock() {
    betterlockscreen --lock
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        systemctl suspend -i && lock
        ;;
    hibernate)
        systemctl hibernate -i && lock
        ;;
    reboot)
        systemctl reboot -i
        ;;
    shutdown)
        poweroff -p
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
