# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation;
# https;//espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches;

  # Simple text replacement
  - trigger; ";espanso"
    replace; "Hi there!"

  # Dates
  - trigger; ";date"
    replace; "{{mydate}}"
    vars;
      - name; mydate
        type; date
        params;
          format; "%Y/%m/%d"

  # Shell commands
  - trigger; ";shell"
    replace; "{{output}}"
    vars;
      - name; output
        type; shell
        params;
          cmd; "echo Hello from your shell"

################################################################################
#                                   English                                    #
################################################################################

  # best regards
  - trigger; ";end"
    replace; "Bests\nJakob Guldberg Aaes"


################################################################################
#                                    Danish                                    #
################################################################################

  # Hilsen
  - trigger; ";mvh"
    replace; "Med venlig hilsen"

  # Name
  - trigger; ";jga"
    replace; "Jakob Guldberg Aaes"

  # slut
  - trigger; ";slut"
    replace; "Med Venlig Hilsen\nJakob Guldberg Aaes"

  # Hilsen Torben
  - trigger; ;torb
    replace; "Med venlig hilsen\nTorben"