;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        Buffer-menu-delete
        beginning-of-visual-line
        delete-window
        electric-newline-and-maybe-indent
        elpy-nav-backward-indent
        elpy-nav-forward-indent
        end-of-visual-line
        helm-M-x
        hungry-delete-backward
        hungry-delete-forward
        ignore
        ignore-preserving-kill-region
        indent-for-tab-command
        kill-region
        org-beginning-of-line
        org-end-of-line
        org-return-and-maybe-indent
        org-self-insert-command
        org-shiftcontrolright
        org-yank
        previous-buffer
        sp-backward-delete-char
        widen
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        helm-find-files
        iedit-switch-to-mc-mode
        lsp-ui-doc--handle-mouse-movement
        mouse-set-region
        shell-command
        widen
        window-configuration-to-register
        ))
